using System.Collections.Generic;
using UnityEngine;
using static UnityEditor.Experimental.GraphView.GraphView;

/// <summary>
/// ï¿½Xï¿½eï¿½[ï¿½Wï¿½ğ¶ï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½X
/// </summary>
public class StageGenerator : MonoBehaviour
{
    Transform _player;
    [SerializeField] StageRowGenerator _stageRowGenerator;
    [SerializeField] LaneObjectGenerator _obstacleGenerator;

    [SerializeField, Tooltip("ï¿½ï¿½{ï¿½ï¿½ï¿½ï¿½")] float _baseWidth = 5;
    [SerializeField, Tooltip("ï¿½Kï¿½wï¿½ï¿½ï¿½ã‚ªï¿½é‚²ï¿½Æ‚É‘ï¿½ï¿½ï¿½ï¿½é‰¡ï¿½ï¿½")] float _widthPerLayer = 1;
    [SerializeField, Tooltip("ï¿½Kï¿½wï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½Ì•ï¿½")] float _heightPerLayer = 5;

    [SerializeField, Tooltip("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Kï¿½wï¿½Ìï¿½")] int _generateLayers = 6;
    [SerializeField, Tooltip("Y=0ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Kï¿½wï¿½i0-originï¿½j")] int _initialLayer = 2;
    [SerializeField, Tooltip("ï¿½ï¿½xï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é‹—ï¿½ï¿½")] float _generateDistance = 100;
    [SerializeField, Tooltip("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½")] float _generatePerMoveDistance = 50;

    List<StageRowGenerator> _generator = new();

    private float _nextGeneratePosX;

    private void Start()
    {
        // get player
        _player = FindAnyObjectByType<PlayerMove>().transform;

        // ï¿½eï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌƒWï¿½Fï¿½lï¿½ï¿½ï¿½[ï¿½^ï¿½[ï¿½ğ¶ï¿½ï¿½Aï¿½vï¿½ï¿½ï¿½pï¿½eï¿½Bï¿½ï¿½ï¿½Zï¿½bï¿½g
        for (int layer = 0; layer < _generateLayers; layer++)
        {
            var space = _baseWidth + _widthPerLayer * layer;
            var height = (layer - _initialLayer) * _heightPerLayer;
            var row = Instantiate(_stageRowGenerator);
            row.Initialize(space, height, layer);
            _generator.Add(row);
        }

        // ï¿½Xï¿½eï¿½[ï¿½Wï¿½ï¿½ï¿½ï¿½
        GenerateStage();

        for ( int layer = 0; layer < _generateLayers; layer++)
        {
            if (_obstacleGenerator != null)
            {
                _obstacleGenerator.Generate(layer);
            }
        }
    }

    private void Update()
    {
        // ï¿½ï¿½è‹—ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½é‚²ï¿½Æ‚Éï¿½ï¿½ï¿½
        if (_player.position.x > _nextGeneratePosX)
        {
            GenerateStage();
        }
    }

    /// <summary>
    /// ï¿½eï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÅƒXï¿½eï¿½[ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B
    /// </summary>
    private void GenerateStage()
    {
        if (Foundation.InGameLane == null) Debug.Log("Foundation.InGameLane is null");

        // var stageParent = new GameObject("Stage").transform;

        foreach (var row in _generator)
        {
            row.Generate(_player.position.x + _generateDistance, row.gameObject.transform);
        }

        _obstacleGenerator.Generate();

        _nextGeneratePosX = _player.position.x + _generatePerMoveDistance;
    }
}
